//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch DM.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DMTYPE                      129
#define IDB_BITMAP_E                    133
#define IDB_BITMAP_ICONS                138
#define IDB_BITMAP_ICONS3D              139
#define IDB_BITMAP_ICONS3DB             140
#define IDB_BITMAP_PCST042              141
#define IDB_BITMAP_RUCK                 142
#define IDB_BITMAP_TREP                 143
#define IDB_BITMAP_PINV                 144
#define IDB_OPEN_SCROLL                 160
#define IDB_OPEN_CHEST                  161
#define IDB_MAGICBG                     162
#define IDB_LEVER_UP_FRONT              163
#define IDB_LEVER_UP_RIGHT              164
#define IDB_LEVER_DOWN_FRONT            165
#define IDB_LEVER_DOWN_RIGHT            166
#define IDB_BITMAP_E2FL                 177
#define IDB_BITMAP_E2FR                 178
#define IDB_BITMAP_E3FL                 185
#define IDB_BITMAP_E3FR                 186
#define IDB_DOOR_FRAME_0                202
#define IDB_DOOR_FRAME_1L               203
#define IDB_DOOR_FRAME_2L               204
#define IDB_DOOR_FRAME_3L               205
#define IDB_DOOR_FRAME_3FL              206
#define IDB_DOOR_FRONT_1T               208
#define IDB_DOOR_FRONT_2T               209
#define IDB_DOOR_IRON_1                 210
#define IDB_DOOR_IRON_2                 211
#define IDB_DOOR_IRON_3                 213
#define IDB_DOOR_IRON_FULL_1            214
#define IDB_DOOR_IRON_FULL_2            215
#define IDB_DOOR_IRON_FULL_3            216
#define IDB_DOOR_RA_1                   217
#define IDB_DOOR_RA_2                   218
#define IDB_DOOR_RA_3                   219
#define IDB_DOOR_WOOD_1                 220
#define IDB_DOOR_WOOD_2                 221
#define IDB_DOOR_WOOD_3                 222
#define IDB_DOOR_SMASHED_1              223
#define IDB_DOOR_SMASHED_2              224
#define IDB_DOOR_SMASHED_3              225
#define IDB_DOOR_SWITCH                 226
#define IDB_DOOR_BLACK_1                227
#define IDB_STAIRS_DOWN_0L              238
#define IDB_STAIRS_DOWN_1F              239
#define IDB_STAIRS_UP_1L                240
#define IDB_STAIRS_UP_0L                241
#define IDB_STAIRS_DOWN_3F              242
#define IDB_STAIRS_UP_1F                243
#define IDB_STAIRS_UP_2L                244
#define IDB_STAIRS_DOWN_2L              245
#define IDB_STAIRS_DOWN_3L              246
#define IDB_STAIRS_DOWN_2F              247
#define IDB_STAIRS_DOWN_1L              248
#define IDB_STAIRS_UP_3F                249
#define IDB_STAIRS_UP_2F                250
#define IDB_STAIRS_UP_3L                251
#define IDB_STAIRS_DOWN_0F              252
#define IDB_STAIRS_UP_0F                253
#define IDB_STAIRS_DOWN_S2L             254
#define IDB_STAIRS_S1L                  255
#define IDB_STAIRS_S3L                  256
#define IDB_STAIRS_UP_S2L               257
#define IDB_ITEMS_42                    258
#define IDB_ITEMS_43                    259
#define IDB_ITEMS_44                    260
#define IDB_ITEMS_45                    261
#define IDB_ITEMS_46                    262
#define IDB_ITEMS_47                    263
#define IDB_ITEMS_48                    264
#define IDB_PRESSURE_PAD_1F             265
#define IDB_PRESSURE_PAD_1L             266
#define IDB_PRESSURE_PAD_2F             267
#define IDB_PRESSURE_PAD_2L             268
#define IDB_PRESSURE_PAD_3F             269
#define IDB_PRESSURE_PAD_3L             270
#define IDB_FLOOR_PUDDLE_F1             271
#define IDB_FLOOR_PUDDLE_L1             272
#define IDB_FLOOR_PUDDLE_F2             273
#define IDB_FLOOR_PUDDLE_L2             274
#define IDB_FLOOR_PUDDLE_F3             275
#define IDB_FLOOR_PUDDLE_L3             276
#define IDB_FLOOR_MOSS_F1               277
#define IDB_FLOOR_MOSS_L1               278
#define IDB_FLOOR_MOSS_F2               279
#define IDB_FLOOR_MOSS_L2               280
#define IDB_FLOOR_MOSS_F3               281
#define IDB_FLOOR_MOSS_L3               282
#define IDB_FLOOR_PIT_CEILING_F0        285
#define IDB_FLOOR_PIT_CEILING_L0        286
#define IDB_FLOOR_PIT_CEILING_F1        287
#define IDB_FLOOR_PIT_CEILING_L1        288
#define IDB_FLOOR_PIT_CEILING_F2        289
#define IDB_FLOOR_PIT_CEILING_L2        290
#define IDB_FLOOR_PIT_INV_F0            291
#define IDB_FLOOR_PIT_INV_L0            292
#define IDB_FLOOR_PIT_INV_F1            293
#define IDB_FLOOR_PIT_INV_L1            294
#define IDB_FLOOR_PIT_INV_F2            295
#define IDB_FLOOR_PIT_INV_L2            296
#define IDB_FLOOR_PIT_F0                297
#define IDB_FLOOR_PIT_L0                298
#define IDB_FLOOR_PIT_F1                299
#define IDB_FLOOR_PIT_L1                300
#define IDB_FLOOR_PIT_F2                301
#define IDB_FLOOR_PIT_L2                302
#define IDB_FLOOR_PIT_F3                303
#define IDB_FLOOR_PIT_L3                304
#define IDB_TELEPORTER                  320
#define IDB_BITMAP_P                    391
#define IDB_ITEM3D_GOLDKEY              400
#define IDB_ITEM3D_IRONKEY              401
#define IDB_ITEM3D_APPLE                402
#define IDB_ITEM3D_BREAD                403
#define IDB_ITEM3D_WATERSKIN_E          404
#define IDB_ITEM3D_WATERSKIN_F          405
#define IDB_ITEM3D_SWORD                406
#define IDB_ITEM3D_CLUB                 407
#define IDB_ITEM3D_CORN                 408
#define IDB_ITEM3D_DAGGER               409
#define IDB_ITEM3D_ARROW                410
#define IDB_ITEM3D_TORCH                411
#define IDB_ITEM3D_LEATHERBOOTS         412
#define IDB_ITEM3D_ELVENDOUBLET         413
#define IDB_ITEM3D_FINEROBE             414
#define IDB_ITEM3D_CHEESE               415
#define IDB_ITEM3D_COMPASS              416
#define IDB_ITEM3D_THROWINGSTAR         417
#define IDB_ITEM3D_POISONDART           418
#define IDB_ITEM3D_SLAYER               419
#define IDB_ITEM3D_AXE                  420
#define IDB_ITEM3D_STONECLUB            421
#define IDB_ITEM3D_SCREAMERSLICE        422
#define IDB_ITEM3D_WORMROUND            423
#define IDB_ITEM3D_BOULDER              424
#define IDB_ITEM3D_ROCK                 425
#define IDB_ITEM3D_LEATHERCLOTH         426
#define IDB_ITEM3D_SCROLL               427
#define IDB_ITEM3D_FLASK_EMPTY          428
#define IDB_ITEM3D_FLASK_FULL           429
#define IDB_ITEM3D_COIN_GOLD            430
#define IDB_ITEM3D_COIN_SILVER          431
#define IDB_ITEM3D_DRUMSTICK            432
#define IDB_ITEM3D_SHIELD_L             433
#define IDB_ITEM3D_SHIELD_S             434
#define IDB_ITEM3D_MAGICBOX_B           435
#define IDB_ITEM3D_MAGICBOX_G           436
#define IDB_ITEM3D_SUEDEBOOTS           437
#define IDB_ITEM3D_SANDALS              438
#define IDB_ITEM3D_BERZERKERHELM        439
#define IDB_ITEM3D_CHEST                440
#define IDB_ITEM3D_CHEST_C              441
#define IDB_ITEM3D_GEM_BLUE             442
#define IDB_ITEM3D_GEM_GREEN            443
#define IDB_ITEM3D_GEM_ORANGE           444
#define IDB_ITEM3D_BONES                445
#define IDB_ITEM3D_IRONBOOTS            446
#define IDB_ITEM3D_IRONHELMET           447
#define IDB_ITEM3D_IRONLEGPLATE         448
#define IDB_ITEM3D_IRONPLATE            449
#define IDB_ITEM3D_BLUE_PANTS           450
#define IDB_ITEM3D_BOOTS_OF_SPEED       451
#define IDB_ITEM3D_CHOKER               452
#define IDB_ITEM3D_CROWN                453
#define IDB_ITEM3D_ELVEN_BOOTS          454
#define IDB_ITEM3D_HELLION              455
#define IDB_ITEM3D_ILLUMUNET            456
#define IDB_ITEM3D_MAIL_AKETON          457
#define IDB_ITEM3D_MOONSTONE            458
#define IDB_ITEM3D_FIRESTAFF            459
#define IDB_ITEM3D_WAND                 460
#define IDB_ITEM3D_RABBITS_FOOT         461
#define IDB_ITEM3D_CONDUIT              462
#define IDB_ITEM3D_CORBAMITE            463
#define IDB_ITEM3D_EYE_OF_TIME          464
#define IDB_ITEM3D_SCEPTRE_OF_LYF       465
#define IDB_ITEM3D_ASHES                466
#define IDB_ITEM3D_VORPAL_BLADE         467
#define IDB_ITEM3D_STICK                468
#define IDB_ITEM3D_CROSSBOW             469
#define IDB_ITEM3D_MACE                 470
#define IDB_ITEM3D_DRAGONSPIT           471
#define IDB_ITEM3D_MORNINGSTAR          472
#define IDB_ITEM3D_FLAMITT              473
#define IDB_ITEM3D_POTION               474
#define IDB_ITEM3D_BOMB                 475
#define IDB_ITEM3D_ROPE                 476
#define IDB_ITEM3D_DRAGON_STEAK         477
#define IDB_ITEM3D_HORN_OF_FEAR         478
#define IDB_ITEM3D_MIRROR               479
#define IDB_ITEM3D_LOCKPICKS            480
#define IDB_ITEM3D_FIRESTAFF_COMPLETE   481
#define IDB_ITEM3D_MAGNIFIER            482
#define IDB_ITEM3D_HALTER               483
#define IDB_ITEM3D_STAFF                484
#define IDB_ITEM3D_BOW                  485
#define IDB_DMG_REC_SMALL               490
#define IDB_DMG_REC_BIG                 491
#define IDB_INTERFACE_DEAD              492
#define IDB_INTERFACE_ALIVE             493
#define IDB_EXPLODE_ANTIMAT             500
#define IDB_EXPLODE_FIREBALL            501
#define IDB_EXPLODE_POISON              502
#define IDB_EXPLODE_DUST                503
#define IDB_ANTIMAT_LIGHT               504
#define IDB_ANTIMAT_MEDIUM              505
#define IDB_ANTIMAT_STRONG              506
#define IDB_FIREBALL_LIGHT              507
#define IDB_INSIDE_FIREBALL_LIGHT       507
#define IDB_FIREBALL_MEDIUM             508
#define IDB_INSIDE_FIREBALL_MEDIUM      508
#define IDB_FIREBALL_STRONG             509
#define IDB_INSIDE_FIREBALL_STRONG      509
#define IDB_POISON_LIGHT                510
#define IDB_INSIDE_POISON_LIGHT         510
#define IDB_POISON_MEDIUM               511
#define IDB_INSIDE_POISON_MEDIUM        511
#define IDB_POISON_STRONG               512
#define IDB_INSIDE_POISON_STRONG        512
#define IDB_MONSTER_WORM_FRONT          528
#define IDB_MONSTER_WORM_ATTACK         532
#define IDB_MONSTER_WORM_BACK           533
#define IDB_MONSTER_WORM_RIGHT          534
#define IDB_MONSTER_GIGGLER_ATTACK      535
#define IDB_MONSTER_GIGGLER_BACK        536
#define IDB_MONSTER_GIGGLER_FRONT       537
#define IDB_MONSTER_GIGGLER_RIGHT       538
#define IDB_CHAMPIONS                   582
#define IDB_MONSTER_SCREAMER_ATTACK     600
#define IDB_MONSTER_SCREAMER_FRONT      601
#define IDB_MONSTER_ROCKPILE_ATTACK     602
#define IDB_MONSTER_ROCKPILE_FRONT      603
#define IDB_MONSTER_MUMMY_BACK          604
#define IDB_MONSTER_MUMMY_FRONT         605
#define IDB_MONSTER_MUMMY_ATTACK        606
#define IDB_MONSTER_MUMMY_RIGHT         607
#define IDB_MONSTER_SKELETON_ATTACK     608
#define IDB_MONSTER_SKELETON_BACK       609
#define IDB_MONSTER_SKELETON_FRONT      610
#define IDB_MONSTER_SKELETON_RIGHT      611
#define IDB_MONSTER_TROLIN_ATTACK       616
#define IDB_MONSTER_TROLIN_BACK         617
#define IDB_MONSTER_TROLIN_FRONT        618
#define IDB_MONSTER_TROLIN_RIGHT        619
#define IDB_MONSTER_PAINRAT_ATTACK      620
#define IDB_MONSTER_PAINRAT_BACK        621
#define IDB_MONSTER_PAINRAT_FRONT       622
#define IDB_MONSTER_PAINRAT_RIGHT       623
#define IDB_MONSTER_GHOST_ATTACK        624
#define IDB_MONSTER_GHOST_FRONT         625
#define IDB_MISSILE_CLUB_B              740
#define IDB_MISSILE_CLUB_F              741
#define IDB_MISSILE_CLUB_S              742
#define IDB_MISSILE_SWORD_B             743
#define IDB_MISSILE_SWORD_F             744
#define IDB_MISSILE_SWORD_S             745
#define IDB_MISSILE_DAGGER_B            750
#define IDB_MISSILE_DAGGER_F            751
#define IDB_MISSILE_DAGGER_S            752
#define IDB_MISSILE_ARROW_B             753
#define IDB_MISSILE_ARROW_F             754
#define IDB_MISSILE_ARROW_S             755
#define IDB_MISSILE_THROWINGSTAR_S      765
#define IDB_MISSILE_THROWINGSTAR_F      766
#define IDB_MISSILE_POISONDART_B        767
#define IDB_MISSILE_POISONDART_S        768
#define IDB_MISSILE_POISONDART_F        769
#define IDB_MISSILE_SLAYER_B            770
#define IDB_MISSILE_SLAYER_S            771
#define IDB_MISSILE_SLAYER_F            772
#define IDB_MISSILE_AXE_B               773
#define IDB_MISSILE_AXE_S               774
#define IDB_MISSILE_AXE_F               775
#define IDB_MISSILE_STONECLUB_B         776
#define IDB_MISSILE_STONECLUB_S         777
#define IDB_MISSILE_STONECLUB_F         778
#define IDB_MISSILE_ANTIMAT             779
#define IDB_MISSILE_FIREBALL            780
#define IDB_MISSILE_POISON              781
#define IDB_MISSILE_POISONBLOB          782
#define IDB_ACTION_INACTIVE             900
#define IDB_ACTIONS_AREA                901
#define IDB_ONE_HAND                    902
#define IDB_ACTIONS_DAMAGE              903
#define IDB_REITER1                     904
#define IDB_REITER2                     905
#define IDB_REITER3                     906
#define IDB_REITER4                     907
#define IDB_RUNES1                      908
#define IDB_RUNES2                      909
#define IDB_RUNES3                      910
#define IDB_RUNES4                      911
#define IDB_BITMAP_E0L                  1001
#define IDB_BITMAP_E0LF                 1002
#define IDB_BITMAP_E0R                  1004
#define IDB_BITMAP_E0RF                 1005
#define IDB_BITMAP_E1L                  1011
#define IDB_BITMAP_E1LF                 1012
#define IDB_BITMAP_E1M                  1013
#define IDB_BITMAP_E1MF                 1014
#define IDB_BITMAP_E1R                  1015
#define IDB_BITMAP_E1RF                 1016
#define IDB_BITMAP_E2L                  1021
#define IDB_BITMAP_E2LF                 1022
#define IDB_BITMAP_E2M                  1023
#define IDB_BITMAP_E2MF                 1024
#define IDB_BITMAP_E2R                  1025
#define IDB_BITMAP_E2RF                 1026
#define IDB_BITMAP_E3L                  1031
#define IDB_BITMAP_E3LF                 1032
#define IDB_BITMAP_E3M                  1033
#define IDB_BITMAP_E3MF                 1034
#define IDB_BITMAP_E3R                  1035
#define IDB_BITMAP_E3RF                 1036
#define IDB_FONT_BLACK                  1501
#define IDB_FONT_WALL                   1502
#define IDB_FONT_WHITE                  1503
#define IDB_FONT_LIGHTGREY              1504
#define IDB_WALLDECO_0F                 2000
#define IDB_WALLDECO_1F                 2001
#define IDB_WALLDECO_2F                 2002
#define IDB_WALLDECO_3F                 2003
#define IDB_WALLDECO_4F                 2004
#define IDB_WALLDECO_5F                 2005
#define IDB_WALLDECO_6F                 2006
#define IDB_WALLDECO_7F                 2007
#define IDB_WALLDECO_8F                 2008
#define IDB_WALLDECO_9F                 2009
#define IDB_WALLDECO_12F                2012
#define IDB_WALLDECO_13F                2013
#define IDB_WALLDECO_14F                2014
#define IDB_WALLDECO_15F                2015
#define IDB_WALLDECO_16F                2016
#define IDB_WALLDECO_17F                2017
#define IDB_WALLDECO_18F                2018
#define IDB_WALLDECO_19F                2019
#define IDB_WALLDECO_20F                2020
#define IDB_WALLDECO_21F                2021
#define IDB_WALLDECO_22F                2022
#define IDB_WALLDECO_23F                2023
#define IDB_WALLDECO_24F                2024
#define IDB_WALLDECO_25F                2025
#define IDB_WALLDECO_26F                2026
#define IDB_WALLDECO_27F                2027
#define IDB_WALLDECO_28F                2028
#define IDB_WALLDECO_29F                2029
#define IDB_WALLDECO_30F                2030
#define IDB_WALLDECO_31F                2031
#define IDB_WALLDECO_32F                2032
#define IDB_WALLDECO_33F                2033
#define IDB_WALLDECO_34F                2034
#define IDB_WALLDECO_35F                2035
#define IDB_WALLDECO_36F                2036
#define IDB_WALLDECO_37F                2037
#define IDB_WALLDECO_38F                2038
#define IDB_WALLDECO_39F                2039
#define IDB_WALLDECO_40F                2040
#define IDB_WALLDECO_41F                2041
#define IDB_WALLDECO_42F                2042
#define IDB_WALLDECO_43F                2043
#define IDB_WALLDECO_44F                2044
#define IDB_WALLDECO_45F                2045
#define IDB_WALLDECO_46F                2046
#define IDB_WALLDECO_47F                2047
#define IDB_WALLDECO_48F                2048
#define IDB_WALLDECO_49F                2049
#define IDB_WALLDECO_50F                2050
#define IDB_WALLDECO_51F                2051
#define IDB_WALLDECO_52F                2052
#define IDB_WALLDECO_53F                2053
#define IDB_WALLDECO_54F                2054
#define IDB_WALLDECO_55F                2055
#define IDB_WALLDECO_56F                2056
#define IDB_WALLDECO_57F                2057
#define IDB_WALLDECO_58F                2058
#define IDB_WALLDECO_59F                2059
#define IDB_WALLDECO_0L                 2100
#define IDB_WALLDECO_1L                 2101
#define IDB_WALLDECO_2L                 2102
#define IDB_WALLDECO_3L                 2103
#define IDB_WALLDECO_4L                 2104
#define IDB_WALLDECO_5L                 2105
#define IDB_WALLDECO_6L                 2106
#define IDB_WALLDECO_7L                 2107
#define IDB_WALLDECO_8L                 2108
#define IDB_WALLDECO_9L                 2109
#define IDB_WALLDECO_12L                2112
#define IDB_WALLDECO_13L                2113
#define IDB_WALLDECO_14L                2114
#define IDB_WALLDECO_15L                2115
#define IDB_WALLDECO_16L                2116
#define IDB_WALLDECO_17L                2117
#define IDB_WALLDECO_18L                2118
#define IDB_WALLDECO_19L                2119
#define IDB_WALLDECO_20L                2120
#define IDB_WALLDECO_21L                2121
#define IDB_WALLDECO_22L                2122
#define IDB_WALLDECO_23L                2123
#define IDB_WALLDECO_24L                2124
#define IDB_WALLDECO_25L                2125
#define IDB_WALLDECO_26L                2126
#define IDB_WALLDECO_27L                2127
#define IDB_WALLDECO_28L                2128
#define IDB_WALLDECO_29L                2129
#define IDB_WALLDECO_30L                2130
#define IDB_WALLDECO_31L                2131
#define IDB_WALLDECO_32L                2132
#define IDB_WALLDECO_33L                2133
#define IDB_WALLDECO_34L                2134
#define IDB_WALLDECO_35L                2135
#define IDB_WALLDECO_36L                2136
#define IDB_WALLDECO_37L                2137
#define IDB_WALLDECO_38L                2138
#define IDB_WALLDECO_39L                2139
#define IDB_WALLDECO_40L                2140
#define IDB_WALLDECO_41L                2141
#define IDB_WALLDECO_42L                2142
#define IDB_WALLDECO_43L                2143
#define IDB_WALLDECO_44L                2144
#define IDB_WALLDECO_45L                2145
#define IDB_WALLDECO_46L                2146
#define IDB_WALLDECO_47L                2147
#define IDB_WALLDECO_48L                2148
#define IDB_WALLDECO_49L                2149
#define IDB_WALLDECO_50L                2150
#define IDB_WALLDECO_51L                2151
#define IDB_WALLDECO_52L                2152
#define IDB_WALLDECO_53L                2153
#define IDB_WALLDECO_54L                2154
#define IDB_WALLDECO_55L                2155
#define IDB_WALLDECO_56L                2156
#define IDB_WALLDECO_57L                2157
#define IDB_WALLDECO_58L                2158
#define IDB_WALLDECO_59L                2159

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        679
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
