//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch DM.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DMTYPE                      129
#define IDB_BITMAP_E                    133
#define IDB_BITMAP_ICONS                138
#define IDB_BITMAP_ICONS3D              139
#define IDB_BITMAP_ICONS3DB             140
#define IDB_BITMAP_PCST042              141
#define IDB_BITMAP_RUCK                 142
#define IDB_BITMAP_TREP                 143
#define IDB_BITMAP_PINV                 144
#define IDB_MAGICBG                     162
#define IDB_LEVER_UP_FRONT              163
#define IDB_LEVER_UP_RIGHT              164
#define IDB_LEVER_DOWN_FRONT            165
#define IDB_LEVER_DOWN_RIGHT            166
#define IDB_BITMAP_E2FL                 177
#define IDB_BITMAP_E2FR                 178
#define IDB_BITMAP_E3FL                 185
#define IDB_BITMAP_E3FR                 186
#define IDB_MONSTER_SCREAMER_ATTACK     187
#define IDB_MONSTER_SCREAMER_FRONT      188
#define IDB_MONSTER_ROCKPILE_ATTACK     189
#define IDB_MONSTER_ROCKPILE_FRONT      190
#define IDB_MONSTER_MUMMY_BACK          193
#define IDB_MONSTER_MUMMY_FRONT         194
#define IDB_MONSTER_MUMMY_ATTACK        195
#define IDB_MONSTER_MUMMY_RIGHT         196
#define IDB_MONSTER_SKELETON_ATTACK     198
#define IDB_MONSTER_SKELETON_BACK       199
#define IDB_MONSTER_SKELETON_FRONT      200
#define IDB_MONSTER_SKELETON_RIGHT      201
#define IDB_DOOR_FRAME_0                202
#define IDB_DOOR_FRAME_1L               203
#define IDB_DOOR_FRAME_2L               204
#define IDB_DOOR_FRAME_3L               205
#define IDB_DOOR_FRAME_3FL              206
#define IDB_DOOR_FRONT_1T               208
#define IDB_DOOR_FRONT_2T               209
#define IDB_DOOR_IRON_1                 210
#define IDB_DOOR_IRON_2                 211
#define IDB_DOOR_IRON_3                 213
#define IDB_ACTIONS_AREA                216
#define IDB_ONE_HAND                    217
#define IDB_ACTIONS_DAMAGE              219
#define IDB_REITER1                     221
#define IDB_REITER2                     222
#define IDB_REITER3                     223
#define IDB_REITER4                     224
#define IDB_RUNES1                      225
#define IDB_RUNES2                      226
#define IDB_RUNES3                      227
#define IDB_RUNES4                      228
#define IDB_STAIRS_DOWN_0L              229
#define IDB_STAIRS_DOWN_1F              230
#define IDB_STAIRS_UP_1L                231
#define IDB_STAIRS_UP_0L                232
#define IDB_STAIRS_DOWN_3F              233
#define IDB_STAIRS_UP_1F                234
#define IDB_STAIRS_UP_2L                235
#define IDB_STAIRS_DOWN_2L              236
#define IDB_STAIRS_DOWN_3L              237
#define IDB_STAIRS_DOWN_2F              238
#define IDB_STAIRS_DOWN_1L              239
#define IDB_STAIRS_UP_3F                240
#define IDB_STAIRS_UP_2F                241
#define IDB_STAIRS_UP_3L                242
#define IDB_STAIRS_DOWN_0F              243
#define IDB_STAIRS_UP_0F                244
#define IDB_STAIRS_DOWN_S2L             245
#define IDB_STAIRS_S1L                  246
#define IDB_STAIRS_S3L                  247
#define IDB_STAIRS_UP_S2L               248
#define IDB_ITEMS_42                    250
#define IDB_ITEMS_43                    251
#define IDB_ITEMS_44                    252
#define IDB_ITEMS_45                    253
#define IDB_ITEMS_46                    254
#define IDB_ITEMS_47                    255
#define IDB_ITEMS_48                    256
#define IDB_DOOR_WOOD_1                 257
#define IDB_DOOR_WOOD_2                 258
#define IDB_DOOR_WOOD_3                 259
#define IDB_DOOR_WOOD_BASHED            260
#define IDB_DOOR_SWITCH                 261
#define IDB_PRESSURE_PAD_1F             265
#define IDB_PRESSURE_PAD_1L             266
#define IDB_PRESSURE_PAD_2F             267
#define IDB_PRESSURE_PAD_2L             268
#define IDB_PRESSURE_PAD_3F             269
#define IDB_PRESSURE_PAD_3L             270
#define IDB_FLOOR_PUDDLE_F1             271
#define IDB_FLOOR_PUDDLE_L1             272
#define IDB_FLOOR_PUDDLE_F2             273
#define IDB_FLOOR_PUDDLE_L2             274
#define IDB_FLOOR_PUDDLE_F3             275
#define IDB_FLOOR_PUDDLE_L3             276
#define IDB_FLOOR_MOSS_F1               277
#define IDB_FLOOR_MOSS_L1               278
#define IDB_FLOOR_MOSS_F2               279
#define IDB_FLOOR_MOSS_L2               280
#define IDB_FLOOR_MOSS_F3               281
#define IDB_FLOOR_MOSS_L3               282
#define IDB_FLOOR_PIT_CEILING_F0        285
#define IDB_FLOOR_PIT_CEILING_L0        286
#define IDB_FLOOR_PIT_CEILING_F1        287
#define IDB_FLOOR_PIT_CEILING_L1        288
#define IDB_FLOOR_PIT_CEILING_F2        289
#define IDB_FLOOR_PIT_CEILING_L2        290
#define IDB_FLOOR_PIT_INV_F0            291
#define IDB_FLOOR_PIT_INV_L0            292
#define IDB_FLOOR_PIT_INV_F1            293
#define IDB_FLOOR_PIT_INV_L1            294
#define IDB_FLOOR_PIT_INV_F2            295
#define IDB_FLOOR_PIT_INV_L2            296
#define IDB_FLOOR_PIT_F0                297
#define IDB_FLOOR_PIT_L0                298
#define IDB_FLOOR_PIT_F1                299
#define IDB_FLOOR_PIT_L1                300
#define IDB_FLOOR_PIT_F2                301
#define IDB_FLOOR_PIT_L2                302
#define IDB_FLOOR_PIT_F3                303
#define IDB_FLOOR_PIT_L3                304
#define IDB_TELEPORTER                  320
#define IDB_BITMAP_P                    391
#define IDB_ITEM3D_GOLDKEY              400
#define IDB_ITEM3D_IRONKEY              401
#define IDB_ITEM3D_APPLE                402
#define IDB_ITEM3D_BREAD                403
#define IDB_ITEM3D_WATERSKIN_E          404
#define IDB_ITEM3D_WATERSKIN_F          405
#define IDB_ITEM3D_SWORD                406
#define IDB_ITEM3D_CLUB                 407
#define IDB_ITEM3D_CORN                 408
#define IDB_ITEM3D_DAGGER               409
#define IDB_ITEM3D_ARROW                410
#define IDB_ITEM3D_TORCH                411
#define IDB_ITEM3D_LEATHERBOOTS         412
#define IDB_ITEM3D_ELVENDOUBLET         413
#define IDB_ITEM3D_FINEROBE             414
#define IDB_ITEM3D_CHEESE               415
#define IDB_ITEM3D_COMPASS              416
#define IDB_ITEM3D_THROWINGSTAR         417
#define IDB_ITEM3D_POISONDART           418
#define IDB_ITEM3D_SLAYER               419
#define IDB_ITEM3D_AXE                  420
#define IDB_ITEM3D_STONECLUB            421
#define IDB_ITEM3D_SCREAMERSLICE        422
#define IDB_MISSILE_CLUB_B              440
#define IDB_MISSILE_CLUB_F              441
#define IDB_MISSILE_CLUB_S              442
#define IDB_MISSILE_SWORD_B             443
#define IDB_MISSILE_SWORD_F             444
#define IDB_MISSILE_SWORD_S             445
#define IDB_MISSILE_DAGGER_B            450
#define IDB_MISSILE_DAGGER_F            451
#define IDB_MISSILE_DAGGER_S            452
#define IDB_MISSILE_ARROW_B             453
#define IDB_MISSILE_ARROW_F             454
#define IDB_MISSILE_ARROW_S             455
#define IDB_MISSILE_THROWINGSTAR_S      465
#define IDB_MISSILE_THROWINGSTAR_F      466
#define IDB_MISSILE_POISONDART_B        467
#define IDB_MISSILE_POISONDART_S        468
#define IDB_MISSILE_POISONDART_F        469
#define IDB_MISSILE_SLAYER_B            470
#define IDB_MISSILE_SLAYER_S            471
#define IDB_MISSILE_SLAYER_F            472
#define IDB_MISSILE_AXE_B               473
#define IDB_MISSILE_AXE_S               474
#define IDB_MISSILE_AXE_F               475
#define IDB_MISSILE_STONECLUB_B         476
#define IDB_MISSILE_STONECLUB_S         477
#define IDB_MISSILE_STONECLUB_F         478
#define IDB_DMG_REC_SMALL               486
#define IDB_DMG_REC_BIG                 487
#define IDB_INTERFACE_DEAD              488
#define IDB_INTERFACE_ALIVE             489
#define IDB_BITMAP_E0L                  1001
#define IDB_BITMAP_E0LF                 1002
#define IDB_BITMAP_E0R                  1004
#define IDB_BITMAP_E0RF                 1005
#define IDB_BITMAP_E1L                  1011
#define IDB_BITMAP_E1LF                 1012
#define IDB_BITMAP_E1M                  1013
#define IDB_BITMAP_E1MF                 1014
#define IDB_BITMAP_E1R                  1015
#define IDB_BITMAP_E1RF                 1016
#define IDB_BITMAP_E2L                  1021
#define IDB_BITMAP_E2LF                 1022
#define IDB_BITMAP_E2M                  1023
#define IDB_BITMAP_E2MF                 1024
#define IDB_BITMAP_E2R                  1025
#define IDB_BITMAP_E2RF                 1026
#define IDB_BITMAP_E3L                  1031
#define IDB_BITMAP_E3LF                 1032
#define IDB_BITMAP_E3M                  1033
#define IDB_BITMAP_E3MF                 1034
#define IDB_BITMAP_E3R                  1035
#define IDB_BITMAP_E3RF                 1036
#define IDB_WALLDECO_1F                 2001
#define IDB_WALLDECO_2F                 2002
#define IDB_WALLDECO_3F                 2003
#define IDB_WALLDECO_4F                 2004
#define IDB_WALLDECO_5F                 2005
#define IDB_WALLDECO_6F                 2006
#define IDB_WALLDECO_7F                 2007
#define IDB_WALLDECO_14F                2014
#define IDB_WALLDECO_15F                2015
#define IDB_WALLDECO_16F                2016
#define IDB_WALLDECO_17F                2017
#define IDB_WALLDECO_18F                2018
#define IDB_WALLDECO_19F                2019
#define IDB_WALLDECO_20F                2020
#define IDB_WALLDECO_21F                2021
#define IDB_WALLDECO_22F                2022
#define IDB_WALLDECO_23F                2023
#define IDB_WALLDECO_24F                2024
#define IDB_WALLDECO_25F                2025
#define IDB_WALLDECO_26F                2026
#define IDB_WALLDECO_27F                2027
#define IDB_WALLDECO_28F                2028
#define IDB_WALLDECO_29F                2029
#define IDB_WALLDECO_30F                2030
#define IDB_WALLDECO_31F                2031
#define IDB_WALLDECO_32F                2032
#define IDB_WALLDECO_33F                2033
#define IDB_WALLDECO_34F                2034
#define IDB_WALLDECO_35F                2035
#define IDB_WALLDECO_36F                2036
#define IDB_WALLDECO_44F                2044
#define IDB_WALLDECO_45F                2045
#define IDB_WALLDECO_47F                2047
#define IDB_WALLDECO_48F                2048
#define IDB_WALLDECO_49F                2049
#define IDB_WALLDECO_50F                2050
#define IDB_WALLDECO_51F                2051
#define IDB_WALLDECO_52F                2052
#define IDB_WALLDECO_53F                2053
#define IDB_WALLDECO_54F                2054
#define IDB_WALLDECO_55F                2055
#define IDB_WALLDECO_1L                 2101
#define IDB_WALLDECO_2L                 2102
#define IDB_WALLDECO_3L                 2103
#define IDB_WALLDECO_4L                 2104
#define IDB_WALLDECO_5L                 2105
#define IDB_WALLDECO_6L                 2106
#define IDB_WALLDECO_7L                 2107
#define IDB_WALLDECO_14L                2114
#define IDB_WALLDECO_15L                2115
#define IDB_WALLDECO_16L                2116
#define IDB_WALLDECO_17L                2117
#define IDB_WALLDECO_18L                2118
#define IDB_WALLDECO_19L                2119
#define IDB_WALLDECO_20L                2120
#define IDB_WALLDECO_21L                2121
#define IDB_WALLDECO_22L                2122
#define IDB_WALLDECO_23L                2123
#define IDB_WALLDECO_24L                2124
#define IDB_WALLDECO_25L                2125
#define IDB_WALLDECO_26L                2126
#define IDB_WALLDECO_27L                2127
#define IDB_WALLDECO_28L                2128
#define IDB_WALLDECO_29L                2129
#define IDB_WALLDECO_30L                2130
#define IDB_WALLDECO_31L                2131
#define IDB_WALLDECO_32L                2132
#define IDB_WALLDECO_33L                2133
#define IDB_WALLDECO_34L                2134
#define IDB_WALLDECO_35L                2135
#define IDB_WALLDECO_36L                2136
#define IDB_WALLDECO_44L                2144
#define IDB_WALLDECO_45L                2145
#define IDB_WALLDECO_47L                2147
#define IDB_WALLDECO_48L                2148
#define IDB_WALLDECO_49L                2149
#define IDB_WALLDECO_50L                2150
#define IDB_WALLDECO_51L                2151
#define IDB_WALLDECO_52L                2152
#define IDB_WALLDECO_53L                2153
#define IDB_WALLDECO_54L                2154
#define IDB_WALLDECO_55L                2155

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        497
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
